### ISSUE TITLE
modules mvn install 报错

### ISSUE THREAD

**Issue by coolrainman** [springside/springside4#267]
D:\learn\springside4\modules>mvn install
..........

[INFO] Springside :: Module :: Parent .................... SUCCESS [1.047s]
[INFO] Springside :: Module :: Test ...................... SUCCESS [36.203s]
[INFO] Springside :: Module :: Core ...................... FAILURE [0.969s]
[INFO] Springside :: Module :: Extension ................. SKIPPED
[INFO] Springside :: Module .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 38.563s
[INFO] Finished at: Sun Sep 08 15:10:50 CST 2013
[INFO] Final Memory: 13M/32M
[INFO] ------------------------------------------------------------------------
[ERROR] Internal error: java.lang.ArrayIndexOutOfBoundsException: 8194 -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.ArrayIndexOutOfBoundsException: 8
194
        at org.apache.maven.lifecycle.internal.BuilderCommon.handleBuildError(BuilderCommon.java:128
)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBu
ilder.java:95)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBu
ilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter
.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 8194
        at org.codehaus.plexus.util.xml.pull.MXParser.parsePI(MXParser.java:2470)
        at org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1257)
        at org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1105)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.nextTag(MavenXpp3Reader.java:808)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parsePluginExecution(MavenXpp3Reader.java:
3105)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parsePlugin(MavenXpp3Reader.java:2918)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parsePluginManagement(MavenXpp3Reader.java
:3186)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parseBuild(MavenXpp3Reader.java:1157)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.parseModel(MavenXpp3Reader.java:2456)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:4088)
        at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:4021)
        at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:122)
        at org.apache.maven.model.io.DefaultModelReader.read(DefaultModelReader.java:91)
        at org.apache.maven.model.building.DefaultModelProcessor.read(DefaultModelProcessor.java:77)

```
    at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:45
```

9)
        at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuil
der.java:864)
        at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:6
70)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:308)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:232)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtif
actDescriptorReader.java:308)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescript
or(DefaultArtifactDescriptorReader.java:172)
        at org.sonatype.aether.impl.internal.DefaultDependencyCollector.process(DefaultDependencyCol
lector.java:419)
        at org.sonatype.aether.impl.internal.DefaultDependencyCollector.process(DefaultDependencyCol
lector.java:533)
        at org.sonatype.aether.impl.internal.DefaultDependencyCollector.collectDependencies(DefaultD
ependencyCollector.java:243)
        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.collectDependencies(DefaultRepo
sitorySystem.java:345)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDepende
nciesResolver.java:131)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(Lifecycle
DependencyResolver.java:171)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencie
s(LifecycleDependencyResolver.java:108)
        at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecut
or.java:258)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:201)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBu
ilder.java:84)
        ... 16 more
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following arti
cles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException

麻烦看看怎么解决，谢谢

**Comment by hellohaojie** [comment]
大佬我遇到了这个问题帮我解决下呗

**Comment by hellohaojie** [comment]
mvn -e -X 报的都是8194错误，而且都是数组越界错误
