### ISSUE TITLE
QuickStart报ShiroDbRealm的错误

### ISSUE THREAD

**Issue by richard2011** [springside/springside4#366]
15:32:10.833 [27756423@qtp-13080585-3] WARN  o.a.shiro.mgt.DefaultSecurityManager - Delegate RememberMeManager instance of type [org.apache.shiro.web.mgt.CookieRememberMeManager] threw an exception during getRememberedPrincipals().
org.apache.shiro.io.SerializationException: Unable to deserialze argument byte array.
    at org.apache.shiro.io.DefaultSerializer.deserialize(DefaultSerializer.java:82) ~[shiro-core-1.2.3.jar:1.2.3]
    at org.apache.shiro.mgt.AbstractRememberMeManager.deserialize(AbstractRememberMeManager.java:514) ~[shiro-core-1.2.3.jar:1.2.3]
    at org.apache.shiro.mgt.AbstractRememberMeManager.convertBytesToPrincipals(AbstractRememberMeManager.java:431) ~[shiro-core-1.2.3.jar:1.2.3]
    at org.apache.shiro.mgt.AbstractRememberMeManager.getRememberedPrincipals(AbstractRememberMeManager.java:396) ~[shiro-core-1.2.3.jar:1.2.3]
    at org.apache.shiro.mgt.DefaultSecurityManager.getRememberedIdentity(DefaultSecurityManager.java:604) [shiro-core-1.2.3.jar:1.2.3]
    at org.apache.shiro.mgt.DefaultSecurityManager.resolvePrincipals(DefaultSecurityManager.java:492) [shiro-core-1.2.3.jar:1.2.3]
    at org.apache.shiro.mgt.DefaultSecurityManager.createSubject(DefaultSecurityManager.java:342) [shiro-core-1.2.3.jar:1.2.3]
    at org.apache.shiro.subject.Subject$Builder.buildSubject(Subject.java:846) [shiro-core-1.2.3.jar:1.2.3]
    at org.apache.shiro.web.subject.WebSubject$Builder.buildWebSubject(WebSubject.java:148) [shiro-web-1.2.3.jar:1.2.3]
    at org.apache.shiro.web.servlet.AbstractShiroFilter.createSubject(AbstractShiroFilter.java:292) [shiro-web-1.2.3.jar:1.2.3]
    at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:359) [shiro-web-1.2.3.jar:1.2.3]
    at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.3.jar:1.2.3]
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344) [spring-web-4.0.4.RELEASE.jar:4.0.4.RELEASE]
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261) [spring-web-4.0.4.RELEASE.jar:4.0.4.RELEASE]
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212) [jetty-6.1.26.jar:6.1.26]
    at org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:177) [spring-orm-4.0.4.RELEASE.jar:4.0.4.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.0.4.RELEASE.jar:4.0.4.RELEASE]
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212) [jetty-6.1.26.jar:6.1.26]
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88) [spring-web-4.0.4.RELEASE.jar:4.0.4.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.0.4.RELEASE.jar:4.0.4.RELEASE]
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.Server.handle(Server.java:326) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410) [jetty-6.1.26.jar:6.1.26]
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582) [jetty-util-6.1.26.jar:6.1.26]
Caused by: java.lang.ClassNotFoundException: Unable to load ObjectStreamClass [org.springside.examples.showcase.service.ShiroDbRealm$ShiroUser: static final long serialVersionUID = -1373760761780840081L;]: 
    at org.apache.shiro.io.ClassResolvingObjectInputStream.resolveClass(ClassResolvingObjectInputStream.java:55) ~[shiro-core-1.2.3.jar:1.2.3]
    at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source) ~[na:1.6.0_30]
    at java.io.ObjectInputStream.readClassDesc(Unknown Source) ~[na:1.6.0_30]
    at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[na:1.6.0_30]
    at java.io.ObjectInputStream.readObject0(Unknown Source) ~[na:1.6.0_30]
    at java.io.ObjectInputStream.readObject(Unknown Source) ~[na:1.6.0_30]
    at java.util.HashSet.readObject(Unknown Source) ~[na:1.6.0_30]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_30]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.6.0_30]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.6.0_30]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.6.0_30]
    at java.io.ObjectStreamClass.invokeReadObject(Unknown Source) ~[na:1.6.0_30]
    at java.io.ObjectInputStream.readSerialData(Unknown Source) ~[na:1.6.0_30]
    at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[na:1.6.0_30]
    at java.io.ObjectInputStream.readObject0(Unknown Source) ~[na:1.6.0_30]
    at java.io.ObjectInputStream.readObject(Unknown Source) ~[na:1.6.0_30]
    at java.util.HashMap.readObject(Unknown Source) ~[na:1.6.0_30]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_30]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.6.0_30]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.6.0_30]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.6.0_30]
    at java.io.ObjectStreamClass.invokeReadObject(Unknown Source) ~[na:1.6.0_30]
    at java.io.ObjectInputStream.readSerialData(Unknown Source) ~[na:1.6.0_30]
    at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[na:1.6.0_30]
    at java.io.ObjectInputStream.readObject0(Unknown Source) ~[na:1.6.0_30]
    at java.io.ObjectInputStream.defaultReadFields(Unknown Source) ~[na:1.6.0_30]
    at java.io.ObjectInputStream.defaultReadObject(Unknown Source) ~[na:1.6.0_30]
    at org.apache.shiro.subject.SimplePrincipalCollection.readObject(SimplePrincipalCollection.java:295) ~[shiro-core-1.2.3.jar:1.2.3]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_30]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.6.0_30]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.6.0_30]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.6.0_30]
    at java.io.ObjectStreamClass.invokeReadObject(Unknown Source) ~[na:1.6.0_30]
    at java.io.ObjectInputStream.readSerialData(Unknown Source) ~[na:1.6.0_30]
    at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[na:1.6.0_30]
    at java.io.ObjectInputStream.readObject0(Unknown Source) ~[na:1.6.0_30]
    at java.io.ObjectInputStream.readObject(Unknown Source) ~[na:1.6.0_30]
    at org.apache.shiro.io.DefaultSerializer.deserialize(DefaultSerializer.java:77) ~[shiro-core-1.2.3.jar:1.2.3]
    ... 34 common frames omitted
Caused by: org.apache.shiro.util.UnknownClassException: Unable to load class named [org.springside.examples.showcase.service.ShiroDbRealm$ShiroUser] from the thread context, current, or system/application ClassLoaders.  All heuristics have been exhausted.  Class could not be found.
    at org.apache.shiro.util.ClassUtils.forName(ClassUtils.java:148) ~[shiro-core-1.2.3.jar:1.2.3]
    at org.apache.shiro.io.ClassResolvingObjectInputStream.resolveClass(ClassResolvingObjectInputStream.java:53) ~[shiro-core-1.2.3.jar:1.2.3]
    ... 71 common frames omitted
为QuickStart会报打showcase的ShiroUser。
可以登陆的

**Comment by zhdevelop** [comment]
解决了我的问题，果然是本地cookie的问题

**Comment by panxiaochao** [comment]
我今天也碰到了，不知道是不是这个问题！
