### ISSUE TITLE
mvn报错.. 是我版本下载有问题吗?

### ISSUE THREAD

**Issue by xwj1003** [springside/springside4#503]
I:\springside4>quick-start.bat
[Pre-Requirement] Makesure install JDK 7.0+ and set the JAVA_HOME.
[Pre-Requirement] Makesure install Maven 3.0.3+ and set the PATH.
[Step 1] Install all springside modules to local maven repository.
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.springside:springside-utils:jar:5.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ io.springside:springside-utils:[unknown-version], I:\springside4\modules\utils\pom.xml, line 99, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ io.springside:springside-utils:[unknown-version], I:\springside4\modules\utils\pom.xml, line 85, column 12
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.springside:springside-core:jar:5.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-enforcer-plugin is missing. @ io.springside:springside-core:[unknown-version], I:\springside4\modules\core\pom.xml, line 174, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ io.springside:springside-core:[unknown-version], I:\springside4\modules\core\pom.xml, line 153, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ io.springside:springside-core:[unknown-version], I:\springside4\modules\core\pom.xml, line 139, column 12
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Springside :: Module
[INFO] Springside :: Module :: Utils
[INFO] Springside :: Module :: Core
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Springside :: Module 5.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ springside-modules ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ springside-modules ---
[INFO] Installing I:\springside4\modules\pom.xml to C:\Users\xwj10\.m2\repository\io\springside\springside-modules\5.0.0-SNAPSHOT\springside-modules-5.0.0-SNAPSHOT.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Springside :: Module :: Utils 5.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ springside-utils ---
[INFO] Deleting I:\springside4\modules\utils\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ springside-utils ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory I:\springside4\modules\utils\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ springside-utils ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 16 source files to I:\springside4\modules\utils\target\classes
[WARNING] /I:/springside4/modules/utils/src/main/java/org/springside/modules/utils/Encodes.java: I:\springside4\modules\utils\src\main\java\org\springside\modules\utils\Encodes.java使用或覆盖了已过时的 API。
[WARNING] /I:/springside4/modules/utils/src/main/java/org/springside/modules/utils/Encodes.java: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
[WARNING] /I:/springside4/modules/utils/src/main/java/org/springside/modules/utils/Exceptions.java: 某些输入文件使用了未经检查或不安全的操作。
[WARNING] /I:/springside4/modules/utils/src/main/java/org/springside/modules/utils/Exceptions.java: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ springside-utils ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ springside-utils ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 12 source files to I:\springside4\modules\utils\target\test-classes
[WARNING] /I:/springside4/modules/utils/src/test/java/org/springside/modules/utils/Collecitons3Test.java: 某些输入文件使用了未经检查或不安全的操作。
[WARNING] /I:/springside4/modules/utils/src/test/java/org/springside/modules/utils/Collecitons3Test.java: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ springside-utils ---
[INFO] Surefire report directory: I:\springside4\modules\utils\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.springside.modules.test.log.LogbackListAppenderTest
15:02:58.948 [main] WARN  o.s.m.t.log.LogbackListAppenderTest - Hello
15:02:58.952 [main] WARN  o.s.m.t.log.LogbackListAppenderTest - World
15:02:58.962 [main] WARN  o.s.m.t.log.LogbackListAppenderTest - Hello
15:02:58.962 [main] WARN  o.s.m.t.log.LogbackListAppenderTest - Hello
15:02:58.962 [main] WARN  o.s.m.t.log.LogbackListAppenderTest - Hello
15:02:58.962 [main] WARN  o.s.m.t.log.LogbackListAppenderTest - Hello
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.24 sec
Running org.springside.modules.utils.Collecitons3Test
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.054 sec
Running org.springside.modules.utils.CryptosTest
aes key in hex            :15216bdd32de391271fb9e3d31685aa6
iv in hex                 :7801f0149fa16cf283e764dc7c42c6bc
aes encrypt in hex result :93707c2d34a6148ab71908a732acd91e
aes key in hex            :df8e9e84b258ace0a005463766abe414
aes encrypt in hex result :174e0ac2f1f2ec5168c998e2def72730
hmac-sha1 key in hex      :fadb9ccde7406223a9254b26471d9735ed2931f1
hmac-sha1 in hex result   :6fb4a66e257ea683976dcda463282f7609f79e09
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.314 sec
Running org.springside.modules.utils.DigestsTest
md5: 74c922f46e07f13c4f705b419dc70803
sha1:da39a3ee5e6b4b0d3255bfef95601890afd80709
murmur32 for user1:-989117379
murmur32 for user2:-114457973
murmur32 with seed for user1:-1018204345
murmur32 with seed for user2:-604914852
sha1 in hex result                               :12dea96fec20593566ab75692c9949596833adc9
salt in hex                                      :2d7b1633e83538e5
sha1 in hex result with salt                     :dfc5fa6d3391b27000ff616e12403a44099509fd
sha1 in hex result with salt and 1024 interations:fdf910ec697a25e0c56429a9b52f39df7f806d0d
crc32 for user1:-1940814507
crc32 for user2:358143215
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.038 sec
Running org.springside.modules.utils.EncodesTest
http%3A%2F%2Flocahost%2F%3Fq%3D%E4%B8%AD%E6%96%87%26t%3D1
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec
Running org.springside.modules.utils.ExceptionsTest
java.lang.RuntimeException: java.lang.Exception: my exception
        at org.springside.modules.utils.ExceptionsTest.getStackTraceAsString(ExceptionsTest.java:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.Exception: my exception
        at org.springside.modules.utils.ExceptionsTest.getStackTraceAsString(ExceptionsTest.java:30)
        ... 29 more

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.08 sec
Running org.springside.modules.utils.IdentitiesTest
uuid: 1ce475d9-5b54-462f-bdf5-b4220a6c6f2a
uuid2:d6fb5ad35b224d8095baeb0e2927693b
randomLong:  944653285772411081
randomBase62:WhzWK73
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.024 sec
Running org.springside.modules.utils.ReflectionsTest
15:02:59.407 [main] WARN  o.s.modules.utils.Reflections - TestBean2's superclass not ParameterizedType
15:02:59.407 [main] WARN  o.s.modules.utils.Reflections - TestBean3's superclass not ParameterizedType
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec
Running org.springside.modules.utils.ThreadsTest
start task
15:02:59.921 [pool-1-thread-1] WARN  test - InterruptedException
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.368 sec <<< FAILURE!
gracefulShutdown(org.springside.modules.utils.ThreadsTest)  Time elapsed: 0.366 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<null> but was:<[WARN] InterruptedException>
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at org.springside.modules.utils.ThreadsTest.gracefulShutdown(ThreadsTest.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Results :

Failed tests:   gracefulShutdown(org.springside.modules.utils.ThreadsTest): expected:<null> but was:<[WARN] InterruptedException>

Tests run: 28, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Springside :: Module ............................... SUCCESS [  0.407 s]
[INFO] Springside :: Module :: Utils ...................... FAILURE [  4.694 s]
[INFO] Springside :: Module :: Core ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.303 s
[INFO] Finished at: 2016-02-25T15:03:00+08:00
[INFO] Final Memory: 16M/365M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project springside-utils: There are test failures.
[ERROR]
[ERROR] Please refer to I:\springside4\modules\utils\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :springside-utils
Error Happen!!
请按任意键继续. . .

**Comment by chinatax** [comment]
我也存在同样问题？求助白衣啊

**Comment by kennedy-han** [comment]
It seems like test failure. try `mvn install -Dmaven.test.skip=true`
