### ISSUE TITLE
BuildFailed

### ISSUE THREAD

**Issue by RuhuiCheng** [springside/springside4#585]
按照说明运行 有错误产生了

read(org.springside.modules.utils.io.IOUtilTest)  Time elapsed: 0.015 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"ABCDEFG[]
]BC"> but was:<"ABCDEFG[
ABC">
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at org.springside.modules.utils.io.IOUtilTest.read(IOUtilTest.java:17)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running org.springside.modules.utils.io.ResourceUtilTest
jar:file:/C:/Repo-Java/springside4/modules/utils/target/surefire/surefirebooter1907045837556548575.jar!/META-INF/MANIFEST.MF
[jar:file:/C:/Repo-Java/springside4/modules/utils/target/surefire/surefirebooter1907045837556548575.jar!/META-INF/MANIFEST.MF, jar:file:/C:/Maven/Repo/org/apache/maven/surefire/surefire-booter/2.12.4/surefire-booter-2.12.4.jar!/META-INF/MANIFEST.MF, jar:file:/C:/Maven/Repo/org/apache/maven/surefire/surefire-api/2.12.4/surefire-api-2.12.4.jar!/META-INF/MANIFEST.MF, jar:file:/C:/Maven/Repo/com/google/guava/guava/20.0/guava-20.0.jar!/META-INF/MANIFEST.MF, jar:file:/C:/Maven/Repo/org/apache/commons/commons-lang3/3.7/commons-lang3-3.7.jar!/META-INF/MANIFEST.MF, jar:file:/C:/Maven/Repo/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar!/META-INF/MANIFEST.MF, jar:file:/C:/Maven/Repo/net/sf/dozer/dozer/5.5.1/dozer-5.5.1.jar!/META-INF/MANIFEST.MF, jar:file:/C:/Maven/Repo/commons-beanutils/commons-beanutils/1.9.1/commons-beanutils-1.9.1.jar!/META-INF/MANIFEST.MF, jar:file:/C:/Maven/Repo/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar!/META-INF/MANIFEST.MF, jar:file:/C:/Maven/Repo/org/slf4j/jcl-over-slf4j/1.7.5/jcl-over-slf4j-1.7.5.jar!/META-INF/MANIFEST.MF,
jar:file:/C:/Maven/Repo/junit/junit/4.12/junit-4.12.jar!/META-INF/MANIFEST.MF, jar:file:/C:/Maven/Repo/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar!/META-INF/MANIFEST.MF, jar:file:/C:/Maven/Repo/org/assertj/assertj-core/2.6.0/assertj-core-2.6.0.jar!/META-INF/MANIFEST.MF, jar:file:/C:/Maven/Repo/org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar!/META-INF/MANIFEST.MF, jar:file:/C:/Maven/Repo/org/objenesis/objenesis/2.1/objenesis-2.1.jar!/META-INF/MANIFEST.MF, jar:file:/C:/Maven/Repo/ch/qos/logback/logback-classic/1.1.8/logback-classic-1.1.8.jar!/META-INF/MANIFEST.MF, jar:file:/C:/Maven/Repo/ch/qos/logback/logback-core/1.1.8/logback-core-1.1.8.jar!/META-INF/MANIFEST.MF]
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 sec
Running org.springside.modules.utils.io.URLResourceTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0 sec <<< FAILURE!
resource(org.springside.modules.utils.io.URLResourceTest)  Time elapsed: 0 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"springside.min=1[]
]pringside.max=10"> but was:<"springside.min=1[
springside.max=10">
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at org.springside.modules.utils.io.URLResourceTest.resource(URLResourceTest.java:16)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running org.springside.modules.utils.misc.IdGeneratorTest
uuid: 018db82c-6089-43d3-8795-36fe436f58f7
uuid2:d30093cf3f5640ce9501f6c946dff80e
randomLong:  6201739972316286283
randomBase64:g09P6yWVlg==
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec
Running org.springside.modules.utils.misc.SamplerTest
sample 10.5% in 10000 hits should close to 1050, actual is 1084
sample 0.5% in 10000 hits should close to 50, actual is 56
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.springside.modules.utils.net.IPUtilTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.springside.modules.utils.net.NetUtilTest
11:55:51.444 [main] INFO  o.s.modules.utils.net.NetUtil - localhost is 192.168.31.182
random port:20001
random port:60180
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.375 sec
Running org.springside.modules.utils.number.MathUtilTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.springside.modules.utils.number.NumberUtilTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.springside.modules.utils.number.RandomUtilTest
syr2f
npXR6hRu
Q6H31
aT7iqZ7W
StWAv
wfhZwsWIq
ExspL
ONjkq
Qfrn-
fZCdoVn"
!?mdv
!XgL T-
-1846972621
1580900934
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec
Running org.springside.modules.utils.number.UnitConverterTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.springside.modules.utils.reflect.BeanMapperTest
11:55:51.506 [main] WARN  org.dozer.config.GlobalSettings - Dozer configuration file not found: dozer.properties.  Using
defaults for all Dozer global properties.
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.203 sec
Running org.springside.modules.utils.reflect.ClassloaderUtilTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.springside.modules.utils.reflect.ClassUtilTest
11:55:51.725 [main] WARN  o.s.modules.utils.reflect.ClassUtil - TestBean2's superclass not ParameterizedType
11:55:51.725 [main] WARN  o.s.modules.utils.reflect.ClassUtil - TestBean3's superclass not ParameterizedType
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.032 sec
Running org.springside.modules.utils.reflect.ReflectionUtilTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 sec
Running org.springside.modules.utils.security.CryptoUtilTest
aes key in hex            :46BD9EC06B0BB827EB1DE28FCE102045
iv in hex                 :C4F9B00824256975E37A3323F87D75DE
aes encrypt in hex result :C61F210190CADE7F9132C6E987AA524B
aes key in hex            :ADB71EF4BDC1F12FADCDC23F6A4B3D20
aes encrypt in hex result :921C92C321C8C902AD9B2FF2768802C5
hmac-sha1 key in hex      :CBA23742FD75C4F12533EC24FA638E667B5531B9
hmac-sha1 in hex result   :5619899975D49D181924B7657307D99A449FE240
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.672 sec
Running org.springside.modules.utils.text.CsvUtilTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.springside.modules.utils.text.EncodeUtilTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.springside.modules.utils.text.EscapeUtilTest
http%3A%2F%2Flocahost%2F%3Fquery%3D%E4%B8%AD%E6%96%87%26t%3D1
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec
Running org.springside.modules.utils.text.HashUtilTest
sha1:sCtJLx2IJNto032AhdkP64t/os4=
sha1 with salt:dImn6SKWm1Th9AJnOxTTPmnLhQA=
sha1 with salt with iteration:SXOaHyVRTSz/jfC2Myv4+9XNiwk=
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.031 sec <<< FAILURE!
hashFile(org.springside.modules.utils.text.HashUtilTest)  Time elapsed: 0 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"[DmSnwK/Fl0Jplrwtm9tfi7cb/js]="> but was:<"[zV5GyYs9TxreIF1wRODMLsA/4Qg]=">
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at org.springside.modules.utils.text.HashUtilTest.hashFile(HashUtilTest.java:50)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running org.springside.modules.utils.text.MoreStringUtilTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.springside.modules.utils.text.StringBuilderHolderTest
Thread-13-1
Thread-13-2
Thread-13-11
Thread-13-22
Thread-20-1
Thread-20-2
Thread-20-11
Thread-20-22
Thread-12-1
Thread-12-2
Thread-12-11
Thread-12-22
Thread-14-1
Thread-14-2
Thread-14-11
Thread-14-22
Thread-17-1
Thread-18-1
Thread-17-2
Thread-18-2
Thread-17-11
Thread-17-22
Thread-19-1
Thread-21-1
Thread-15-1
Thread-16-1
Thread-15-2
Thread-21-2
Thread-19-2
Thread-21-11
Thread-19-11
Thread-18-11
Thread-19-22
Thread-21-22
Thread-15-11
Thread-16-2
Thread-15-22
Thread-18-22
Thread-16-11
Thread-16-22
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 sec
Running org.springside.modules.utils.text.TextValidatorTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.springside.modules.utils.text.WildcardMatcherTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.springside.modules.utils.time.CachingDatFormatterTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.springside.modules.utils.time.ClockUtilTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 sec
Running org.springside.modules.utils.time.DateFormatUtilTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running org.springside.modules.utils.time.DateUtilTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec
systemShutdowning

Results :

Failed tests:   read(org.springside.modules.utils.io.IOUtilTest): expected:<"ABCDEFG[](..)
  resource(org.springside.modules.utils.io.URLResourceTest): expected:<"springside.min=1[](..)
  hashFile(org.springside.modules.utils.text.HashUtilTest): expected:<"[DmSnwK/Fl0Jplrwtm9tfi7cb/js]="> but was:<"[zV5GyYs9TxreIF1wRODMLsA/4Qg]=">

Tests run: 171, Failures: 3, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Springside :: Module :: Utils ...................... FAILURE [ 15.589 s]
[INFO] Springside :: Module :: Core ....................... SKIPPED
[INFO] Springside :: Module :: Metrics .................... SKIPPED
[INFO] Springside :: Module ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.792 s
[INFO] Finished at: 2018-03-03T11:55:52+08:00
[INFO] Final Memory: 20M/196M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project springside-utils: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Repo-Java\springside4\modules\utils\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error Happen!!
请按任意键继续. . .

**Comment by gitGksgk** [comment]
same error, see #503

**Comment by gitGksgk** [comment]
看来光加个skip有些包出不来，不过有的test failure可能性质不同 #567
